name: Build and Publish Docker Image

on:
  push:
    branches:
      - "dev"

  # release:
  #   types: [published]

jobs:
  push_to_registry:
    name: Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/tennex-io/draw-image-export2:latest
